GET http://localhost:4000/ReportEhs/all
###
POST http://localhost:4000/ReportEhs
Content-Type: application/json

{
    "tipoEvento" : "ef",
    "fname" : "",
    "areaEvento" : "ife ",
    "descripcionEvento" : "ofe",
    "accionCorrectivaPropuesta" : "ufeff",
    "responsableAccionCorrectivaPropuesta" : "zfef",
    "quienRecibeElReporte" : "xfefe",
    "actosInseguros" : "yfefef",
    "condicionesInseguras" : "rfefe"
}
###
DELETE  http://localhost:4000/ReportEhs/delete/6476247e6ddbffaeb9448048
###

